# Generated by Django 5.0.2 on 2024-02-24 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Matc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('first_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_team_matches', to='app.team')),
                ('second_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='second_team_matches', to='app.team')),
            ],
        ),
    ]
